replacers:
  - search: 'IVYPORTAL-(\d+)'
    replace: '[IVYPORTAL-$1](https://1ivy.atlassian.net/browse/IVYPORTAL-$1)'

changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '📦 Dependencies'
      label: 'dependencies'
    - title: ⚠️ Changes
      labels:
        - deprecated
    - title: 📄 Documentation
      labels:
        - docs
        - documentation
  exclude:
    labels:
      - skip-changelog
  template: |
    ## 🚀 New Features
    $CHANGES(feature)

    ## 🐛 Bug Fixes
    $CHANGES(bug)

    ## 📦 Maintenance
    $CHANGES(chore)

