changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '📦 Dependencies'
      label: 'dependencies'
    - title: ⚠️ Changes
      labels:
        - deprecated
    - title: 📄 Documentation
      labels:
        - docs
        - documentation
  exclude:
    labels:
      - skip-changelog
  replacers:
    - search: '/MARP-(\d+)/g'
      replace: '[MARP-$1](https://1ivy.atlassian.net/browse/MARP-$1)'
  template: |
    ## Changes
  
    $CHANGES
