name: Cron bot
run-name: 🤖 Cron bot walking 
on:
  workflow_dispatch:  
  schedule:
    # Cron at midnight UTC
    - cron: '50 8 * * *'

jobs:
  trigger-portal-document-master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sourceBranch: ['master', 'release/10.0']
    steps:
      - uses: actions/github-script@v6
        name: Trigger build Portal Documentation for ${{ matrix.sourceBranch }}
        if: github.event.schedule == '30 8 * * *'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: '${{ matrix.sourceBranch }}'
            })
