name: Cron bot

on:
  workflow_dispatch:
  schedule:
    - cron: '22 7 * * *'
    - cron: '21 7 * * *'
jobs:
  trigger-first-workflow:
    runs-on: loc-pc
    steps:
      - name: Chay luc 7h02
        if: github.event.schedule == '22 7 * * *'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: 'release/10.0'
            })

  trigger-second-workflow:
    runs-on: loc-pc
    steps:
      - name: Chay luc 7h03
        if: github.event.schedule == '21 7 * * *'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: 'master'
            })
