name: Cron bot

on:
  workflow_dispatch:
  schedule:
    # First cron at midnight UTC
    - cron: '45 11 * * *'
    # Second cron at midnight UTC
    - cron: '50 11 * * *'
jobs:
  first-midnight-job:
    runs-on: loc-pc
    steps:     
      - name: Run first midnight task
        run: echo "Running first midnight task"
        
  second-midnight-job:
    runs-on: loc-pc
    steps:        
      - name: Run second midnight task
        run: echo "Running second midnight task"

  trigger-first-workflow:
    runs-on: loc-pc
    steps:
      - name: Trigger first workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: 'release/10.0'
            })

  trigger-second-workflow:
    runs-on: loc-pc
    steps:
      - name: Trigger second workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test-workflow.yml',
              ref: 'master'
            })
