name: Test cron workflow

on:
  workflow_dispatch:

jobs:
  first-midnight-job:
    runs-on: loc-pc
    steps:     
      - name: Run first midnight task
        run: |
          echo "Running first midnight task"
        
        
  second-midnight-job:
    runs-on: loc-pc
    steps:        
      - name: Run second midnight task
        run: echo "Running second midnight task"

